2019-11-24 09:26:08,866 ERROR [in /Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kevinchemutai/Documents/microblog/app/routes.py", line 97, in edit_profile
    db.session.commit()
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/kevinchemutai/Documents/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('kchemutai2', 'I am a computer science student learning python and flask and currently a software QA', 2)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-11-24 09:26:51,950 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:43]
2019-11-28 16:45:42,241 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:43]
2019-11-28 16:47:03,132 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:43]
2019-11-28 16:50:45,915 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:43]
2019-11-28 16:51:21,004 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:43]
2019-11-28 16:52:44,638 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:43]
2019-11-28 16:53:51,176 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:43]
2019-11-28 18:06:49,850 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:43]
2019-12-04 06:30:40,523 INFO [in /Users/kevinchemutai/Documents/microblog/app/__init__.py:45]
2019-12-13 12:30:28,475 INFO [in /Users/kevinchemutai/Desktop/microblog_without_translations/app/__init__.py:52]
2020-02-12 16:31:31,727 INFO: Microblog startup [in /Users/kevinchemutai/Desktop/microblog/app/__init__.py:77]
2020-02-12 16:45:15,274 INFO: Microblog startup [in /Users/kevinchemutai/Desktop/microblog/app/__init__.py:77]
